apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: cloud-platform
    role: alert-rules
  name: cloud-platform-reports
  namespace: concourse-main
spec:
  groups:
  - name: cloud-platform-reports
    rules:
    - record: job:kube_job_status_start_time_cloud_platform:max
      expr: |
        label_replace(
          label_replace(
            max by (job_name, owner_name, namespace)(
              kube_job_status_start_time{namespace=~"concourse-main"}
              * ON(job_name, namespace) GROUP_RIGHT()
              kube_job_owner{namespace=~"concourse-main", owner_name!=""}
            )
            == ON(owner_name) GROUP_LEFT()
            max by (owner_name)(
              kube_job_status_start_time{namespace=~"concourse-main"}
              * ON(job_name, namespace) GROUP_RIGHT()
              kube_job_owner{namespace=~"concourse-main",owner_name!=""}
            ),
          "job", "$1", "job_name", "(.+)"),
        "cronjob", "$1", "owner_name", "(.+)")
    - record: job:kube_job_status_failed_cloud_platform:sum
      expr: |
        clamp_max(
          job:kube_job_status_start_time_cloud_platform:max,
        1)
        * ON(job) GROUP_LEFT()
        label_replace(
          label_replace(
            ((kube_job_status_failed{namespace=~"concourse-main"} != 0)
              * ON(job_name, namespace) GROUP_RIGHT()
              kube_job_owner{namespace=~"concourse-main", owner_name!=""}),
            "job", "$1", "job_name", "(.+)"),
          "cronjob", "$1", "owner_name", "(.+)")
    - alert: CronJobStatusFailed
      annotations:
        dashboard_url: https://grafana.manager.cloud-platform.service.justice.gov.uk/d/application-alerts/application-alerts?orgId=1&var-namespace=concourse-main
        message: CronJob {{ $labels.namespace }}/{{ $labels.cronjob }} is failing.
        runbook_url: https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/tree/main/cloud-platform-reports-cronjobs/templates
        summary: CronJob is failing.
      expr: |
        job:kube_job_status_failed_cloud_platform:sum
        * ON(cronjob, namespace) GROUP_RIGHT()
        kube_cronjob_labels
        > 0
      for: 15m
      labels:
        severity: warning
    - alert: KubeCronJobRunning
      annotations:
        dashboard_url: https://grafana.manager.cloud-platform.service.justice.gov.uk/d/application-alerts/application-alerts?orgId=1&var-namespace=concourse-main
        message: CronJob {{ $labels.namespace }}/{{ $labels.cronjob }} is taking more
          than 1h to complete.
        runbook_url: https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/tree/main/cloud-platform-reports-cronjobs/templates
        summary: CronJob taking a long time to complete.
      expr: time() - kube_cronjob_next_schedule_time{job="kube-state-metrics", namespace=~"concourse-main"}
        > 3600
      for: 1h
      labels:
        severity: warning
    - alert: KubeJobCompletion
      annotations:
        message: Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more
          than 30mins to complete.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobcompletion
      expr: kube_job_spec_completions{job="kube-state-metrics", namespace="concourse-main"} - kube_job_status_succeeded{job="kube-state-metrics", namespace="concourse-main"}  > 0
      for: 30m
      labels:
        severity: warning
    - alert: KubeJobFailed
      annotations:
        message: Job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobfailed
      expr: kube_job_status_failed{job="kube-state-metrics", namespace="concourse-main"}  > 0
      for: 1h
      labels:
        severity: warning
    - alert: KubePodCrashLooping
      annotations:
        message: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
      expr: rate(kube_pod_container_status_restarts_total{namespace="concourse-main", job="kube-state-metrics"}[15m]) * 60 * 5 > 0
      for: 1h
      labels:
        severity: warning
