slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: '#lower-priority-alarms'
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: 'Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title: '$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title_link: 'https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME'
  footer: concourse.cloud-platform.service.justice.gov.uk

resources:
- name: cloud-platform-infrastructure-repo
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-infrastructure.git
    branch: main
    git_crypt_key: ((cloud-platform-infrastructure-git-crypt.key))
- name: tools-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-tools
    tag: "1.43"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-hook-id))

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))

slack_failure_notification: &slack_failure_notification
  put: slack-alert
  params:
    <<: *SLACK_NOTIFICATION_DEFAULTS
    attachments:
      - color: "danger"
        <<: *SLACK_ATTACHMENTS_DEFAULTS

common_params: &common_params
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
  AWS_REGION: eu-west-2
  AWS_PROFILE: moj-cp
  AUTH0_DOMAIN: "justice-cloud-platform.eu.auth0.com"
  AUTH0_CLIENT_ID: ((concourse-tf-auth0-credentials.client-id))
  AUTH0_CLIENT_SECRET: ((concourse-tf-auth0-credentials.client_secret))
  KOPS_STATE_STORE: s3://cloud-platform-kops-state
  KUBE_CONFIG_PATH: ~/.kube/config

groups:
- name: cluster-test
  jobs:
    - build-kops-test-cluster
    - build-eks-test-cluster

jobs:
  - name: build-kops-test-cluster
    serial: true
    plan:
      - in_parallel:
        - get: cloud-platform-infrastructure-repo
          trigger: false
        - get: tools-image
          trigger: false
      - task: build-kops-test-cluster
        image: tools-image
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
          - name: cloud-platform-infrastructure-repo
            path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                mkdir ${HOME}/.aws
                echo "[moj-cp]" >> ${HOME}/.aws/credentials # Cheating create-cluster.rb script, it forces you to have profiles :-(
                export CLUSTER_NAME=cp-$(date +%d%m-%H%M)
                echo "Executing: ./create-cluster.rb --no-gitcrypt -n $CLUSTER_NAME -v $CLUSTER_NAME -t 900 --no-integration-test"
                ./create-cluster.rb --no-gitcrypt -n $CLUSTER_NAME -v $CLUSTER_NAME -t 900 --no-integration-test
        on_failure: *slack_failure_notification

  - name: build-eks-test-cluster
    serial: true
    plan:
      - in_parallel:
        - get: cloud-platform-infrastructure-repo
          trigger: false
        - get: tools-image
          trigger: false
      - task: build-eks-test-cluster
        image: tools-image
        config:
          platform: linux
          params:
            <<: *common_params            
          inputs:
          - name: cloud-platform-infrastructure-repo
            path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                mkdir ${HOME}/.aws
                echo "[moj-cp]" >> ${HOME}/.aws/credentials # Cheating create-cluster.rb script, it forces you to have profiles :-(
                export CLUSTER_NAME=cp-$(date +%d%m-%H%M)
                echo "Executing: ./create-cluster.rb --kind eks --no-gitcrypt -n $CLUSTER_NAME -v $CLUSTER_NAME -t 900 --no-integration-test"
                ./create-cluster.rb --kind eks --no-gitcrypt -n $CLUSTER_NAME -v $CLUSTER_NAME -t 900 --no-integration-test
        on_failure: *slack_failure_notification
