aws-credentials: &AWS_CREDENTIALS
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
  AWS_REGION: eu-west-2

slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: "#lower-priority-alarms"
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: "Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME"
  title: "$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME"
  title_link: "https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
  footer: concourse.cloud-platform.service.justice.gov.uk

resources:
  - name: go-delete-snapshots-image
    type: registry-image
    source:
      repository: webops/delete-oldsnapshots
      tag: "1.0.0"
      aws_region: "eu-west-2"
      aws_access_key_id: ((aws-creds.access-key-id))
      aws_secret_access_key: ((aws-creds.secret-access-key))
  - name: every-24-hours
    type: time
    source:
      interval: 24h
  - name: slack-alert
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/((slack-hook-id))

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))

jobs:
  - name: delete-old-snapshots
    serial: true
    plan:
      - in_parallel:
          - get: every-24-hours
            trigger: true
          - get: go-delete-snapshots-image
      - task: delete-older-snapshots
        image: go-delete-snapshots-image
        config:
          platform: linux
          params:
            <<: *AWS_CREDENTIALS
          run:
            path: /delete-oldsnapshots
            args:
              - -days-old
              - "380"
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
