slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: "#lower-priority-alarms"
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: "Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME"
  title: "$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME"
  title_link: "https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
  footer: concourse.cloud-platform.service.justice.gov.uk

resources:
  - name: cloud-platform-infrastructure-repo
    type: git
    source:
      uri: https://github.com/ministryofjustice/cloud-platform-infrastructure.git
      branch: main
      git_crypt_key: ((cloud-platform-infrastructure-git-crypt.key))
  - name: cloud-platform-cli
    type: registry-image
    source:
      repository: ministryofjustice/cloud-platform-cli
      tag: "1.49.3"
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))
  - name: slack-alert
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/((slack-hook-id))
  - name: every-4-hours
    type: time
    source:
      interval: 4h

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))

groups:
  - name: divergence
    jobs:
      - divergence-eks-manager
      - divergence-eks-live
      - divergence-eks-manager-core
      - divergence-eks-live-core
      - divergence-eks-manager-components
      - divergence-eks-live-components
      - divergence-networking
      - divergence-account-live
      - divergence-global-resources

common_params: &common_params
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
  AWS_REGION: eu-west-2
  AUTH0_DOMAIN: "justice-cloud-platform.eu.auth0.com"
  AUTH0_CLIENT_ID: ((concourse-tf-auth0-credentials.client-id))
  AUTH0_CLIENT_SECRET: ((concourse-tf-auth0-credentials.client_secret))

aws_params_moj_cp: &aws_params_moj_cp
  AWS_PROFILE: moj-cp

terraform-shared: &TERRAFORM_SHARED
  TF_VAR_github_owner: "ministryofjustice"
  TF_VAR_github_token: ((github-actions-secrets-token.token))

auth0: &AUTH0_CONF
  AUTH0_DOMAIN: "justice-cloud-platform.eu.auth0.com"
  AUTH0_CLIENT_ID: ((concourse-tf-auth0-credentials.client-id))
  AUTH0_CLIENT_SECRET: ((concourse-tf-auth0-credentials.client_secret))

jobs:
  - name: divergence-eks-live
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
      - task: check-divergence-eks-live
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks
                cloud-platform terraform check-divergence --workspace live --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-eks-manager
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-eks
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks
                cloud-platform terraform check-divergence --workspace manager --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-eks-live-core
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-eks-live-core
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                (
                  aws eks --region eu-west-2 update-kubeconfig --name live
                )
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks/core
                cloud-platform terraform check-divergence --workspace live --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-eks-live-components
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-eks-live-components
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                (
                  aws eks --region eu-west-2 update-kubeconfig --name live
                )
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components
                cloud-platform terraform check-divergence --workspace live --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-eks-manager-core
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-eks-manager-core
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                (
                  aws eks --region eu-west-2 update-kubeconfig --name manager
                )
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks/core
                cloud-platform terraform check-divergence --workspace manager --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-eks-manager-components
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-eks-manager-components
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                (
                  aws eks --region eu-west-2 update-kubeconfig --name manager
                )
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components
                cloud-platform terraform check-divergence --workspace manager --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-networking
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-networking
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd terraform/aws-accounts/cloud-platform-aws/vpc
                cloud-platform terraform check-divergence --workspace live-1 --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-account-live
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-account-live
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: [*common_params, *aws_params_moj_cp, *TERRAFORM_SHARED]
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile moj-cp
                aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile moj-cp
                cd terraform/aws-accounts/cloud-platform-aws/account
                cloud-platform terraform check-divergence --workspace default --skip-version-check
          outputs:
            - name: metadata
        # on_failure:
        #   put: slack-alert
        #   params:
        #     <<: *SLACK_NOTIFICATION_DEFAULTS
        #     attachments:
        #       - color: "danger"
        #         <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-global-resources
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-account-live
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: [*common_params, *aws_params_moj_cp, *TERRAFORM_SHARED, *AUTH0_CONF]
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile moj-cp
                aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile moj-cp
                cd terraform/global-resources
                cloud-platform terraform check-divergence --workspace default --skip-version-check
          outputs:
            - name: metadata
        # on_failure:
        #   put: slack-alert
        #   params:
        #     <<: *SLACK_NOTIFICATION_DEFAULTS
        #     attachments:
        #       - color: "danger"
        #         <<: *SLACK_ATTACHMENTS_DEFAULTS
