slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: '#lower-priority-alarms'
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: 'Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title: '$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title_link: 'https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME'
  footer: concourse.cloud-platform.service.justice.gov.uk

resources:
- name: cloud-platform-infrastructure-repo
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-infrastructure.git
    branch: main
    git_crypt_key: ((cloud-platform-infrastructure-git-crypt.key))
- name: cloud-platform-cli
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-cli
    tag: "1.9.8"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-hook-id))
- name: every-4-hours
  type: time
  source:
    interval: 4h


resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))

groups:
- name: divergence
  jobs:
    - divergence-kops
    - divergence-eks
    - divergence-eks-components
    - divergence-networking
    - divergence-kops-components


jobs:
  - name: divergence-eks
    serial: true
    plan:
      - in_parallel:
        - get: every-4-hours
          trigger: true
        - get: cloud-platform-infrastructure-repo
          trigger: false
        - get: cloud-platform-cli
          trigger: false
      - task: check-divergence-eks
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            AWS_REGION: eu-west-2
            AUTH0_DOMAIN: "justice-cloud-platform.eu.auth0.com"
            AUTH0_CLIENT_ID: ((concourse-tf-auth0-credentials.client-id))
            AUTH0_CLIENT_SECRET: ((concourse-tf-auth0-credentials.client_secret))
          inputs:
          - name: cloud-platform-infrastructure-repo
            path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks
                cloud-platform terraform check-divergence --workspace manager --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-eks-components
    serial: true
    plan:
      - in_parallel:
        - get: every-4-hours
          trigger: true
        - get: cloud-platform-infrastructure-repo
          trigger: false
        - get: cloud-platform-cli
          trigger: false
      - task: check-divergence-eks-components
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            AWS_REGION: eu-west-2
            KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
            KUBECONFIG_S3_KEY: kubeconfig
            KUBECONFIG: /tmp/kubeconfig
            KUBE_CONFIG_PATH: /tmp/kubeconfig
            KUBE_CLUSTER: manager.cloud-platform.service.justice.gov.uk
            KUBE_CTX: manager.cloud-platform.service.justice.gov.uk
          inputs:
          - name: cloud-platform-infrastructure-repo
            path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                (
                  aws s3 cp s3://cloud-platform-concourse-kubeconfig/kubeconfig /tmp/kubeconfig
                  kubectl config use-context ${KUBE_CLUSTER}
                )
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks/components
                cloud-platform terraform check-divergence --workspace manager --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-kops
    serial: true
    plan:
      - in_parallel:
        - get: every-4-hours
          trigger: true
        - get: cloud-platform-infrastructure-repo
          trigger: false
        - get: cloud-platform-cli
          trigger: false
      - task: check-divergence-kops
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            AWS_REGION: eu-west-2
            AUTH0_DOMAIN: "justice-cloud-platform.eu.auth0.com"
            AUTH0_CLIENT_ID: ((concourse-tf-auth0-credentials.client-id))
            AUTH0_CLIENT_SECRET: ((concourse-tf-auth0-credentials.client_secret))
            KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
            KUBECONFIG_S3_KEY: kubeconfig
            KUBECONFIG: /tmp/kubeconfig
            KUBE_CONFIG_PATH: /tmp/kubeconfig
            KUBE_CLUSTER: live-1.cloud-platform.service.justice.gov.uk
          inputs:
          - name: cloud-platform-infrastructure-repo
            path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                aws s3 cp s3://${KUBECONFIG_S3_BUCKET}/${KUBECONFIG_S3_KEY} /tmp/kubeconfig
                kubectl config use-context ${KUBE_CLUSTER}
                cd terraform/aws-accounts/cloud-platform-aws/vpc/kops
                cloud-platform terraform check-divergence --workspace live-1 --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-networking
    serial: true
    plan:
      - in_parallel:
        - get: every-4-hours
          trigger: true
        - get: cloud-platform-infrastructure-repo
          trigger: false
        - get: cloud-platform-cli
          trigger: false
      - task: check-divergence-networking
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            AWS_REGION: eu-west-2
          inputs:
          - name: cloud-platform-infrastructure-repo
            path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd terraform/aws-accounts/cloud-platform-aws/vpc
                cloud-platform terraform check-divergence --workspace live-1 --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-kops-components
    serial: true
    plan:
      - in_parallel:
        - get: every-4-hours
          trigger: true
        - get: cloud-platform-infrastructure-repo
          trigger: false
        - get: cloud-platform-cli
          trigger: false
      - task: check-divergence-kops-components
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            AWS_REGION: eu-west-2
            KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
            KUBECONFIG_S3_KEY: kubeconfig
            KUBECONFIG: /tmp/kubeconfig
            KUBE_CONFIG_PATH: /tmp/kubeconfig
            KUBE_CLUSTER: live-1.cloud-platform.service.justice.gov.uk
          inputs:
          - name: cloud-platform-infrastructure-repo
            path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                aws s3 cp s3://${KUBECONFIG_S3_BUCKET}/${KUBECONFIG_S3_KEY} /tmp/kubeconfig
                kubectl config use-context ${KUBE_CLUSTER}
                cd terraform/aws-accounts/cloud-platform-aws/vpc/kops/components
                cloud-platform terraform check-divergence --workspace live-1 --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
