slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: "#lower-priority-alarms"
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: "Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME"
  title: "$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME"
  title_link: "https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
  footer: concourse.cloud-platform.service.justice.gov.uk

resources:
  - name: cloud-platform-infrastructure-repo
    type: git
    source:
      uri: https://github.com/ministryofjustice/cloud-platform-infrastructure.git
      branch: main
      git_crypt_key: ((cloud-platform-infrastructure-git-crypt.key))
  - name: cloud-platform-cli
    type: registry-image
    source:
      repository: ministryofjustice/cloud-platform-cli
      tag: "1.49.0"
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))
  - name: slack-alert
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/((slack-hook-id))
  - name: every-4-hours
    type: time
    source:
      interval: 4h

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))

groups:
  - name: divergence-live-2
    jobs:
      - divergence-eks-live-2
      - divergence-eks-live-2-core
      - divergence-eks-live-2-components
      - divergence-networking-live-2

common_params: &common_params
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
  AWS_REGION: eu-west-2
  AUTH0_DOMAIN: "justice-cloud-platform.eu.auth0.com"
  AUTH0_CLIENT_ID: ((concourse-tf-auth0-credentials.client-id))
  AUTH0_CLIENT_SECRET: ((concourse-tf-auth0-credentials.client_secret))

jobs:
  - name: divergence-eks-live-2
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
      - task: check-divergence-eks-live-2
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks
                cloud-platform terraform check-divergence --workspace live-2 --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-eks-live-2-core
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-eks-live-2-core
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                (
                  aws eks --region eu-west-2 update-kubeconfig --name live-2
                )
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks/core
                cloud-platform terraform check-divergence --workspace live-2 --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-eks-live-2-components
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-eks-live-2-components
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                (
                  aws eks --region eu-west-2 update-kubeconfig --name live-2
                )
                cd terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components
                cloud-platform terraform check-divergence --workspace live-2 --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
  - name: divergence-networking-live-2
    serial: true
    build_log_retention:
      days: 31
    plan:
      - in_parallel:
          - get: every-4-hours
            trigger: true
          - get: cloud-platform-infrastructure-repo
            trigger: false
          - get: cloud-platform-cli
            trigger: false
      - task: check-divergence-networking-live-2
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure-repo
              path: ./
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd terraform/aws-accounts/cloud-platform-aws/vpc
                cloud-platform terraform check-divergence --workspace live-2 --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
