slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: '#lower-priority-alarms'
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: 'Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title: '$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title_link: 'https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME'
  footer: concourse.cloud-platform.service.justice.gov.uk

resources:
- name: cloud-platform-infrastructure-repo
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-infrastructure.git
    branch: main
- name: cloud-platform-environments-repo
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-environments.git
    branch: main
    git_crypt_key: ((cloud-platform-environments-git-crypt.key))
- name: cloud-platform-terraform-bastion-repo
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-terraform-bastion.git
    branch: main
- name: tools-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-tools
    tag: "1.43"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-hook-id))
- name: every-1h-during-workdays
  type: time
  source:
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    interval: 1h
    start: 8:00 AM
    stop: 5:00 PM
- name: every-1h-between-midnight-3am
  type: time
  source:
    interval: 1h
    start: 00:00 AM
    stop: 03:00 AM
- name: every-day
  type: time
  source:
    interval: 24h
- name: every-30m
  type: time
  source:
    interval: 30m
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))

groups:
- name: maintenance
  jobs:
    - recycle-node-live-1
    - delete-manually-created-pods-live-1
    - delete-excess-dns
    - update-authorized-keys
    - delete-completed-jobs

jobs:
  - name: recycle-node-live-1
    serial: true
    plan:
      - in_parallel:
        - get: every-1h-between-midnight-3am
          trigger: true
        - get: tools-image
        - get: cloud-platform-infrastructure-repo
          trigger: false
      - task: recycle-oldest-node-live-1
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-infrastructure-repo
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            AWS_REGION: eu-west-2
            KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
            KUBECONFIG_S3_KEY: kubeconfig
            KUBECONFIG: /tmp/kubeconfig
            K8S_CLUSTER_NAME: live-1.cloud-platform.service.justice.gov.uk
          run:
            path: /bin/sh
            dir: cloud-platform-infrastructure-repo
            args:
              - -c
              - |
                aws s3 cp s3://${KUBECONFIG_S3_BUCKET}/${KUBECONFIG_S3_KEY} /tmp/kubeconfig
                kubectl config use-context ${K8S_CLUSTER_NAME}
                ./recycle-node.rb
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS

  - name: delete-manually-created-pods-live-1
    serial: true
    plan:
      - in_parallel:
        - get: every-day
          trigger: true
        - get: cloud-platform-environments-repo
        - get: tools-image
      - task: run-script
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-environments-repo
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            KUBECONFIG: /tmp/kubeconfig
            PIPELINE_CLUSTER: live-1.cloud-platform.service.justice.gov.uk
          run:
            path: /bin/sh
            dir: cloud-platform-environments-repo
            args:
              - -c
              - |
                aws s3 cp s3://cloud-platform-concourse-kubeconfig/kubeconfig /tmp/kubeconfig
                bundle install --without development test
                ./bin/delete_manually_created_pods.rb

        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS

  - name: delete-excess-dns
    serial: true
    plan:
      - in_parallel:
        - get: every-day
          trigger: true
        - get: tools-image
        - get: cloud-platform-environments-repo
      - task: run-script
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-environments-repo
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            AWS_REGION: eu-west-2
            KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
            KUBECONFIG_S3_KEY: kubeconfig
            KUBECONFIG: /tmp/kubeconfig
            K8S_CLUSTER_NAME: live-1.cloud-platform.service.justice.gov.uk
          run:
            path: /bin/sh
            dir: cloud-platform-environments-repo
            args:
              - -c
              - |
                aws s3 cp s3://${KUBECONFIG_S3_BUCKET}/${KUBECONFIG_S3_KEY} /tmp/kubeconfig
                kubectl config use-context ${K8S_CLUSTER_NAME}
                ./bin/delete_unused_dns_records.rb
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS

  - name: update-authorized-keys
    serial: true
    plan:
      - in_parallel:
        - get: every-1h-during-workdays
          trigger: true
        - get: tools-image
        - get: cloud-platform-terraform-bastion-repo
      - task: run-script 
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-terraform-bastion-repo
          params:
            GITHUB_TOKEN: ((authorized-keys-github-token.token)) 
          run:
            path: /bin/sh
            dir: cloud-platform-terraform-bastion-repo
            args:
              - -c
              - |
                ./bin/update-authorized-keys.rb
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS

  - name: delete-completed-jobs
    serial: true
    plan:
      - in_parallel:
        - get: every-30m
          trigger: true
        - get: cloud-platform-environments-repo
        - get: tools-image
      - task: run-script-delete-completed-jobs
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-environments-repo
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            KUBECONFIG: /tmp/kubeconfig
            PIPELINE_CLUSTER: live-1.cloud-platform.service.justice.gov.uk
          run:
            path: /bin/sh
            dir: cloud-platform-environments-repo
            args:
              - -c
              - |
                aws s3 cp s3://cloud-platform-concourse-kubeconfig/kubeconfig /tmp/kubeconfig
                bundle install --without development test
                ./bin/delete_completed_jobs.rb

        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
