aws-credentials: &AWS_CREDENTIALS
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
  AWS_REGION: eu-west-2

kube-config: &KUBECONFIG_PARAMS
  KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
  KUBECONFIG_S3_KEY: kubeconfig
  KUBECONFIG: /tmp/kubeconfig

slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: "#lower-priority-alarms"
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: "Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME"
  title: "$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME"
  title_link: "https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
  footer: concourse.cloud-platform.service.justice.gov.uk

resources:
  - name: cloud-platform-cli
    type: registry-image
    source:
      repository: ministryofjustice/cloud-platform-cli
      tag: "1.39.5"
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))
  - name: go-delete-snapshots-image
    type: docker-image
    source:
      repository: ministryofjustice/delete-oldsnapshots
      tag: "1.5"
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))
  - name: tools-image
    type: docker-image
    source:
      repository: ministryofjustice/cloud-platform-tools
      tag: "2.9.9"
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))
  - name: slack-alert
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/((slack-hook-id))
  - name: every-1h-between-midnight-3am
    type: time
    source:
      interval: 1h
      start: 00:00 AM
      stop: 03:00 AM
  - name: every-hour
    type: time
    source:
      interval: 1h
  - name: every-24-hours
    type: time
    source:
      interval: 24h
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))

groups:
  - name: maintenance
    jobs:
      - live-recycle-node
      - live-delete-completed-jobs
      - delete-old-snapshots

jobs:
  - name: live-recycle-node
    serial: true
    plan:
      - in_parallel:
          - get: every-1h-between-midnight-3am
            trigger: true
          - get: cloud-platform-cli
      - task: recycle-oldest-node
        image: cloud-platform-cli
        config:
          platform: linux
          params:
            <<: [*AWS_CREDENTIALS, *KUBECONFIG_PARAMS]
            K8S_CLUSTER_NAME: live.cloud-platform.service.justice.gov.uk
          run:
            path: /bin/sh
            args:
              - -c
              - |
                aws s3 cp s3://${KUBECONFIG_S3_BUCKET}/${KUBECONFIG_S3_KEY} /tmp/kubeconfig
                kubectl config use-context ${K8S_CLUSTER_NAME}

                cloud-platform cluster recycle-node --oldest --debug --kubecfg /tmp/kubeconfig --skip-version-check
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS

  - name: live-delete-completed-jobs
    serial: true
    plan:
      - in_parallel:
          - get: every-hour
            trigger: true
          - get: tools-image
      - task: run-script-delete-completed-jobs
        image: tools-image
        config:
          platform: linux
          params:
            <<: [*AWS_CREDENTIALS, *KUBECONFIG_PARAMS]
          run:
            path: /bin/sh
            args:
              - -c
              - |
                aws eks --region eu-west-2 update-kubeconfig --name live
                /delete_job --kubeconfig /tmp/kubeconfig
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS

  - name: delete-old-snapshots
    serial: true
    plan:
      - in_parallel:
          - get: every-24-hours
            trigger: true
          - get: go-delete-snapshots-image
      - task: delete-older-snapshots
        image: go-delete-snapshots-image
        config:
          platform: linux
          params:
            <<: *AWS_CREDENTIALS
          run:
            path: /delete-oldsnapshots
            args:
              - -days-old
              - "380"
          outputs:
            - name: metadata
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
