aws-credentials: &AWS_CREDENTIALS
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
  AWS_REGION: eu-west-2
  AWS_PROFILE: moj-cp

slack: &SLACK_BOT_PARAMS
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/((slack-hook-id))

resources:
  - name: tools-image
    type: docker-image
    source:
      repository: ministryofjustice/cloud-platform-tools
      tag: "2.11.0"
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))
  - name: cloud-platform-infra-repo
    type: git
    source:
      uri: https://github.com/ministryofjustice/cloud-platform-infrastructure.git
      branch: main
      git_crypt_key: ((cloud-platform-infrastructure-git-crypt.key))
  - name: morning-9am
    type: time
    source:
      days: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
      start: 9:00 AM
      stop: 9:02 AM
      location: Europe/London
  - name: nightly-11pm
    type: time
    source:
      days: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
      start: 11:00 PM
      stop: 11:02 PM
      location: Europe/London
  - name: nightly-10pm
    type: time
    source:
      days: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
      start: 10:00 PM
      stop: 10:02 PM
      location: Europe/London
  - name: every-360m
    type: time
    source:
      interval: 360m

groups:
  - name: opensearch-app-logs
    jobs:
      - handle-stuck-indices
      - handle-indices-with-no-policy
      - opensearch-indices-health-check
      - live-opensearch-takes-snapshot
      - separate-opensearch-restores-snapshot
jobs:
  - name: handle-stuck-indices
    plan:
      - in_parallel:
          - get: nightly-11pm
            trigger: true
          - get: tools-image
          - get: cloud-platform-infra-repo
      - task: retrigger-failed-warm-to-cold-migrations
        timeout: 2h
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-infra-repo
          params:
            <<:
              [
                *AWS_CREDENTIALS,
              ]
          run:
            path: /bin/bash
            args:
              - -c
              - |
                export AWS_SESSION_TOKEN=""
                mkdir cold_indices_json
                ./warm/fix.sh true
            dir: cloud-platform-infra-repo/scripts/opensearch/stuck-indices

      - task: handle-failed-hot-to-warm-migrations
        timeout: 2h
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-infra-repo
          params:
            <<:
              [
                *AWS_CREDENTIALS,
              ]
          run:
            dir: cloud-platform-infra-repo/scripts/opensearch/stuck-indices
            path: /bin/bash
            args:
            - -c
            - |
              export AWS_SESSION_TOKEN=""
              ./hot/fix.sh true

  - name: handle-indices-with-no-policy
    plan:
      - in_parallel:
          - get: nightly-10pm
            trigger: true
          - get: tools-image
          - get: cloud-platform-infra-repo
      - task: handle-indices-with-no-policy
        timeout: 2h
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-infra-repo
          params:
            <<:
              [
                *AWS_CREDENTIALS,
              ]
          run:
            dir: cloud-platform-infra-repo/scripts/opensearch/policies
            path: /bin/bash
            args:
              - -c
              - |
                export AWS_SESSION_TOKEN=""
                ./fix.sh true
  - name: opensearch-indices-health-check
    plan:
      - in_parallel:
          - get: morning-9am
            trigger: true
          - get: tools-image
          - get: cloud-platform-infra-repo
      - task: opensearch-indices-health-check
        timeout: 2h
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-infra-repo
          params:
            <<:
              [
                *AWS_CREDENTIALS,
                *SLACK_BOT_PARAMS
              ]
          run:
            path: /bin/bash
            args:
              - -c
              - |
                export AWS_SESSION_TOKEN=""
                mkdir cold_indices_json
                ./alert.sh true
            dir: cloud-platform-infra-repo/scripts/opensearch/alert
  - name: live-opensearch-takes-snapshot
    serial: true
    plan:
      - in_parallel:
          - get: every-360m
            trigger: true
          - get: tools-image
          - get: cloud-platform-infra-repo
      - task: live-opensearch-takes-snapshot
        timeout: 6h
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-infra-repo
          params:
            <<:
              [
                *AWS_CREDENTIALS
              ]
          run:
            path: /bin/bash
            args:
              - -c
              - |
                export AWS_SESSION_TOKEN=""
                ./take_snapshot_cold_indices.sh true
            dir: cloud-platform-infra-repo/scripts/opensearch/snapshots/take_snapshots
  - name: separate-opensearch-restores-snapshot
    serial: true
    plan:
      - in_parallel:
          - get: every-360m
            trigger: true
          - get: tools-image
          - get: cloud-platform-infra-repo
      - task: separate-opensearch-restores-snapshot
        timeout: 6h
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-infra-repo
          params:
            <<:
              [
                *AWS_CREDENTIALS
              ]
          run:
            path: /bin/bash
            args:
              - -c
              - |
                export AWS_SESSION_TOKEN=""
                mkdir cold_indices_json
                ./restore_snapshot.sh true
            dir: cloud-platform-infra-repo/scripts/opensearch/snapshots/restore_snapshots