resources:
  - name: cloud-platform-cli-image
    type: registry-image
    source:
      repository: ministryofjustice/cloud-platform-cli
      tag: "1.44.1"
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))

aws_params: &aws_params
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
  AWS_REGION: eu-west-2

groups:
  - name: tag-velero-snapshots
    jobs:
      - tag-velero-snapshots

jobs:
- name: tag-velero-snapshots
  plan:
  - get: cloud-platform-cli-image
  - task: tag-velero-snapshots
    timeout: 48h
    image: cloud-platform-cli-image
    config:
      platform: linux
      params:
        <<: [*aws_params]
      run:
        path: /bin/bash
        args:
        - -c
        - |
          BUSINESS_UNIT_TAG="business-unit"
          BUSINESS_UNIT_VALUE="Platforms"
          SERVICE_AREA_TAG="service-area"
          SERVICE_AREA_VALUE="Hosting"

          echo "Fetching EBS snapshots..."
          SNAPSHOTS=$(aws ec2 describe-snapshots --owner-ids self --query "Snapshots[*].{SnapshotId:SnapshotId,Tags:Tags}" --output json)

          echo "$SNAPSHOTS" | jq -c '.[]' | while read -r SNAPSHOT; do
            SNAPSHOT_ID=$(echo "$SNAPSHOT" | jq -r '.SnapshotId')
            TAGS=$(echo "$SNAPSHOT" | jq -c '.Tags // []')

            BACKUP_TAG=$(echo "$TAGS" | jq -r '.[] | select(.Key == "velero.io/backup") | .Value')
            BUSINESS_UNIT_EXISTS=$(echo "$TAGS" | jq -r '.[] | select(.Key == "'"$BUSINESS_UNIT_TAG"'") | .Key')
            SERVICE_AREA_EXISTS=$(echo "$TAGS" | jq -r '.[] | select(.Key == "'"$SERVICE_AREA_TAG"'") | .Key')

            if [[ -n "$BACKUP_TAG" && -z "$BUSINESS_UNIT_EXISTS" && -z "$SERVICE_AREA_EXISTS" ]]; then
              echo "Updating tags for snapshot: $SNAPSHOT_ID"
              aws ec2 create-tags --resources "$SNAPSHOT_ID" --tags \
                Key="$BUSINESS_UNIT_TAG",Value="$BUSINESS_UNIT_VALUE" \
                Key="$SERVICE_AREA_TAG",Value="$SERVICE_AREA_VALUE"
            fi
          done