resources:
  - name: cloud-platform-infrastructure
    type: git
    source:
      uri: https://github.com/ministryofjustice/cloud-platform-infrastructure.git
      branch: create-cluster
      git_crypt_key: ((cloud-platform-infrastructure-git-crypt.key))
  - name: cloud-platform-infrastructure-image
    type: docker-image
    source:
      repository: ministryofjustice/cloud-platform-infrastructure
      tag: "2.2.4-rc"
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))

common_params: &common_params
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
  AWS_REGION: eu-west-2
  AWS_PROFILE: moj-cp
  AUTH0_DOMAIN: "justice-cloud-platform.eu.auth0.com"
  AUTH0_CLIENT_ID: ((concourse-tf-auth0-credentials.client-id))
  AUTH0_CLIENT_SECRET: ((concourse-tf-auth0-credentials.client_secret))

groups:
  - name: test-cluster
    jobs:
      - create

jobs:
  - name: create
    serial: true
    plan:
      - in_parallel:
          - get: cloud-platform-infrastructure
          - get: cloud-platform-infrastructure-image
      - task: create-test-cluster
        image: cloud-platform-infrastructure-image
        config:
          platform: linux
          params:
            <<: *common_params
          inputs:
            - name: cloud-platform-infrastructure
          run:
            path: /bin/bash
            dir: cloud-platform-infrastructure
            args:
              - -c
              - |
                git clone https://github.com/ministryofjustice/cloud-platform-cli.git
                cd cloud-platform-cli; git checkout create-cluster; make; ls -latr; mv cloud-platform* ../; cd ../
                ./cloud-platform cluster create --name jb-2608-1520 --skip-version-check --fast
