resources:
  - name: tools-image
    type: docker-image
    source:
      repository: ministryofjustice/cloud-platform-tools
      tag: "2.9.0"
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))
  - name: every-week
    type: time
    source:
      days: [Saturday]
      start: 11:00 PM
      stop: 11:30 PM
      location: Europe/London

aws-credentials: &AWS_CREDENTIALS
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
  AWS_REGION: eu-west-2

kube-config: &KUBECONFIG_PARAMS
  KUBECONFIG: /tmp/kubeconfig
  KUBECONFIG_CLUSTER_NAME: ((cluster_name))

groups:
  - name: generate-vulnerability-reports
    jobs:
      - manager
      - live

jobs:
  - name: manager
    plan:
      - in_parallel:
          - get: every-week
            trigger: true
          - get: tools-image
      - task: generate-manager-vulnerability-report
        timeout: 30m
        image: tools-image
        config:
          platform: linux
          run:
            path: /bin/bash
            args:
              - -c
              - |
                set -e

                mkdir ${HOME}/.aws
                echo "[moj-cp]" >> ${HOME}/.aws/credentials # This forces you to have profiles
                
                aws eks --region eu-west-2 update-kubeconfig --name manager

  - name: live
    plan:
      - in_parallel:
          - get: every-week
            trigger: true
          - get: tools-image
      - task: generate-live-vulnerability-report
        timeout: 30m
        image: tools-image
        config:
          platform: linux
          run:
            path: /bin/bash
            args:
              - -c
              - |
                set -e

                mkdir ${HOME}/.aws
                echo "[moj-cp]" >> ${HOME}/.aws/credentials # This forces you to have profiles
                
                aws eks --region eu-west-2 update-kubeconfig --name live

