resources:
  - name: tools-image
    type: docker-image
    source:
      repository: ministryofjustice/cloud-platform-tools
      tag: "2.9.4"
      username: ((ministryofjustice-dockerhub.dockerhub_username))
      password: ((ministryofjustice-dockerhub.dockerhub_password))
  - name: cloud-platform-infrastructure-repo
    type: git
    source:
      uri: https://github.com/ministryofjustice/cloud-platform-infrastructure.git
      branch: main
      git_crypt_key: ((cloud-platform-infrastructure-git-crypt.key))
  - name: every-week
    type: time
    source:
      days: [Saturday]
      start: 11:00 PM
      stop: 11:02 PM
      location: Europe/London

aws-credentials: &AWS_CREDENTIALS
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
  AWS_REGION: eu-west-2

groups:
  - name: generate-vulnerability-reports
    jobs:
      - manager
      - live

jobs:
  - name: manager
    plan:
      - in_parallel:
          - get: every-week
            trigger: true
          - get: tools-image
          - get: cloud-platform-infrastructure-repo
      - task: generate-manager-vulnerability-report
        timeout: 1h
        image: tools-image
        config:
          platform: linux
          params:
            <<: [*AWS_CREDENTIALS]
          inputs:
            - name: cloud-platform-infrastructure-repo
          run:
            path: /bin/bash
            args:
              - -c
              - |
                set -e

                mkdir ${HOME}/.aws
                echo "[moj-cp]" >> ${HOME}/.aws/credentials # This forces you to have profiles
                
                aws eks --region eu-west-2 update-kubeconfig --name manager

                ./cloud-platform-infrastructure-repo/scripts/generate_cluster_vuln_report.sh manager

  - name: live
    plan:
      - in_parallel:
          - get: every-week
            trigger: true
          - get: tools-image
          - get: cloud-platform-infrastructure-repo
      - task: generate-live-vulnerability-report
        timeout: 2h
        image: tools-image
        config:
          platform: linux
          params:
            <<: [*AWS_CREDENTIALS]
          inputs:
            - name: cloud-platform-infrastructure-repo
          run:
            path: /bin/bash
            args:
              - -c
              - |
                set -e

                mkdir ${HOME}/.aws
                echo "[moj-cp]" >> ${HOME}/.aws/credentials # This forces you to have profiles
                
                aws eks --region eu-west-2 update-kubeconfig --name live

                ./cloud-platform-infrastructure-repo/scripts/generate_cluster_vuln_report.sh live
